name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          rsync -avz --delete ./ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/home/${{ secrets.VM_USER }}/demo-node-app/

      - name: Start App
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            cd ~/demo-node-app
            npm install

            pm2 delete demo-app || true
            pm2 start app.js --name demo-app
            pm2 save
          EOF
